version: '3.3'

services:
  db:
    image: yarins2000/petshopdb:1.0
    restart: always
  app:
    depends_on:
      - db
    image: yarins2000/petshopapp:1.0
    ports: 
        - "3000:80" 
        - "3001:433"
    restart: always
